PawMotors/Models/ErrorViewModel.cs
namespace PawMotors.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PawMotors/Controllers/CarsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using Newtonsoft.Json.Linq;
using PawMotors.Entity;
using PawMotors.ProjeContext;

namespace PawMotors.Controllers
{
    public class CarsController : Controller
    {
        Context context = new Context();
        [HttpGet]
        public JsonResult GetCars()
        {
            var cars = context.Cars.ToList();
            return Json(cars);
        }
        public IActionResult Index()
        {
            var values = context.Cars.ToList();
            return View(values);
        }

        [HttpGet] //sayfa yüklendiği zaman çalış
        public IActionResult AddCar()
        {
            return View();
        }
        [HttpPost]
        public JsonResult AddCar([FromBody] Cars newCar)
        {
            if (ModelState.IsValid)
            {
                context.Cars.Add(newCar);
                context.SaveChanges();
                return Json(new { success = true, message = "Car added successfully!" });
            }
            return Json(new { success = false, message = "Invalid data!" });
        }

        public IActionResult DeleteCar(int id)
        {
            var value = context.Cars.Where(x => x.Id == id).FirstOrDefault();
            context.Remove(value);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult UpdateCar(int id)
        {
            var value = context.Cars.Where(x => x.Id == id).FirstOrDefault();
            return View(value);
        }
        [HttpPost]
        public IActionResult UpdateCar(Cars car)
        {
            var value = context.Cars.Where(x => x.Id == car.Id).FirstOrDefault();
            value.Brand = car.Brand;
            value.Model = car.Model;
            value.Year = car.Year;
            value.Color = car.Color;
            value.Price = car.Price;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

PawMotors/Controllers/CustomersController.cs
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using PawMotors.Entity;
using PawMotors.ProjeContext;

namespace PawMotors.Controllers
{
    public class CustomersController : Controller
    {
        Context context = new Context();
        public IActionResult Index()
        {
            var values = context.Customers.ToList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddCustomer()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddCustomer(Customers customer)
        {
            if (customer.FirstName.Length >= 6 && customer.EMail != "")
            {
                context.Add(customer);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }

        }
        public IActionResult DeleteCustomer(int id)
        {
            var value = context.Customers.Where(x => x.Id == id).FirstOrDefault();
            context.Remove(value);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult UpdateCustomer(int id)
        {
            var value = context.Customers.Where(x => x.Id == id).FirstOrDefault();
            return View(value);
        }
        [HttpPost]
        public IActionResult UpdateCustomer(Customers customer)
        {
            var value = context.Customers.Where(x => x.Id == customer.Id).FirstOrDefault();
            value.FirstName = customer.FirstName;
            value.LastName = customer.LastName;
            value.BirthDay = customer.BirthDay;
            value.PhoneNumber = customer.PhoneNumber;
            value.EMail = customer.EMail;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

PawMotors/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PawMotors.Entity;
using PawMotors.Models;
using System.Diagnostics;

namespace PawMotors.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        [HttpGet]
        public IActionResult GetAll(Customers customers)
        {
            ViewBag.Customers = customers.FirstName;
            return View(customers);
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PawMotors/Views/Cars/AddCar.cshtml
@model PawMotors.Entity.Cars

@{
    ViewData["Title"] = "AddCar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Araç Ekleme Sayfası</h1>

<form method="post">
    @Html.Label("Araç Markası")
    @Html.TextBoxFor(x => x.Brand, new { @class = "form-control"})
    <br />
    @Html.Label("Araç Modeli")
    @Html.TextBoxFor(x => x.Model, new { @class = "form-control" })
    <br />
    @Html.Label("Model Yılı")
    @Html.TextBoxFor(x => x.Year, new { @class = "form-control" })
    <br />
    @Html.Label("Renk")
    @Html.TextBoxFor(x => x.Color, new { @class = "form-control" })
    <br />
    @Html.Label("Fiyat")
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
    <br />
    <button class="btn btn-outline-success">Aracı Kaydet</button>
</form>

PawMotors/Views/Cars/Index.cshtml
@using PawMotors.Entity
@model List<Cars>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<h1>Araba Listesi</h1>

<table id="carsTable" class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Marka</th>
            <th>Model</th>
            <th>Yıl</th>
            <th>Renk</th>
            <th>Fiyat</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                url: '@Url.Action("GetCars", "Cars")',
                type: 'GET',
                dataType: 'json',
                success: function (data) {
                    var rows = '';
                    $.each(data, function (index, car) {
                        rows += '<tr>' +
                            '<td>' + car.id + '</td>' +
                            '<td>' + car.brand + '</td>' +
                            '<td>' + car.model + '</td>' +
                            '<td>' + car.year + '</td>' +
                            '<td>' + car.color + '</td>' +
                            '<td>' + car.price + '</td>' +
                            '</tr>';
                    });
                    $('#carsTable tbody').html(rows);
                },
                error: function (error) {
                    console.log(error);
                }
            });
        });
    </script>
}

@*

<h1>Araç Sayfası</h1>


<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Marka</th>
        <th>Model</th>
        <th>Yıl</th>
        <th>Renk</th>
        <th>Fiyat</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach(var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Brand</td>
            <td>@item.Model</td>
            <td>@item.Year</td>
            <td>@item.Color</td>
            <td>@item.Price</td>
            <td><a href="/Cars/DeleteCar/@item.Id" class="btn btn-danger">Sil</a></td>
            <td><a href="/Cars/UpdateCar/@item.Id" class="btn btn-success">Güncelle</a></td>
        </tr>
    }
    <a asp-controller="Cars" asp-action="AddCar" class="btn btn-primary">Yeni Araç Ekle</a>
</table> *@

PawMotors/Views/Cars/UpdateCar.cshtml
@model PawMotors.Entity.Cars
@{
    ViewData["Title"] = "UpdateCar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Araba Güncelleme Sayfası</h1>

<form method="post">
    @Html.Label("Araç ID")
    @Html.TextBoxFor(x => x.Id, new { @class = "form-control" })
    <br />
    @Html.Label("Araç Marka")
    @Html.TextBoxFor(x => x.Brand, new { @class = "form-control" })
    <br />
    @Html.Label("Araç Modeli")
    @Html.TextBoxFor(x => x.Model, new { @class = "form-control" })
    <br />
    @Html.Label("Model Yılı")
    @Html.TextBoxFor(x => x.Year, new { @class = "form-control" })
    <br />
    @Html.Label("Renk")
    @Html.TextBoxFor(x => x.Color, new { @class = "form-control" })
    <br />
    @Html.Label("Fiyat")
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
</form>

PawMotors/Views/Customers/AddCustomer.cshtml
@model PawMotors.Entity.Customers
@{
    ViewData["Title"] = "AddCustomer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Yeni Müşteri Sayfası</h1>


<form method="post">
    @Html.Label("Müşteri Adı")
    @Html.TextBoxFor(x=>x.FirstName, new {@class="form-control"})
    <br />
    @Html.Label("Müşteri Soyadı")
    @Html.TextBoxFor(x => x.LastName, new { @class = "form-control" })
    <br />
    @Html.Label("Doğum Tarihi")
    @Html.TextBoxFor(x => x.BirthDay, new { @class = "form-control" })
    <br />
    @Html.Label("Telefon Numarası")
    @Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control" })
    <br />
    @Html.Label("Mail Adresi")
    @Html.TextBoxFor(x => x.EMail, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Kaydet</button>
</form>

PawMotors/Views/Customers/Index.cshtml
@using PawMotors.Entity
@model List<Customers>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Müşteri Listesi</h1>

<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Müşteri Adı</th>
        <th>Müşteri Soyadı</th>
        <th>Doğum Tarihi</th>
        <th>Telefon Numarası</th>
        <th>Mail Adresi</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.FirstName</td>
            <td>@item.LastName</td>
            <td>@item.BirthDay</td>
            <td>@item.PhoneNumber</td>
            <td>@item.EMail</td>
            <td><a href="/Customers/DeleteCustomer/@item.Id" class="btn btn-danger">Sil</a></td>
            <td><a href="/Customers/UpdateCustomer/@item.Id" class="btn btn-success">Güncelle</a></td>
        </tr>
    }
</table>
<a href="/Customers/AddCustomer" class="btn btn-primary">Yeni Müşteri Girişi</a>

PawMotors/Views/Customers/UpdateCustomer.cshtml
@model PawMotors.Entity.Customers
@{
    ViewData["Title"] = "UpdateCustomer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Müşteri Güncelleme Sayfası</h1>

<form method="post">
    @Html.Label("Müşteri Id")
    @Html.TextBoxFor(x => x.Id, new { @class = "form-control"})
    <br />
    @Html.Label("Müşteri Adı")
    @Html.TextBoxFor(x => x.FirstName, new { @class = "form-control" })
    <br />
    @Html.Label("Müşteri Soyadı")
    @Html.TextBoxFor(x => x.LastName, new { @class = "form-control" })
    <br />
    @Html.Label("Doğum Tarihi")
    @Html.TextBoxFor(x => x.BirthDay, new { @class = "form-control" })
    <br />
    @Html.Label("Telefon Numarası")
    @Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control" })
    <br />
    @Html.Label("Mail Adresi")
    @Html.TextBoxFor(x => x.EMail, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
</form>

PawMotors/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<table>
    <tr>
        <td>

        </td>
    </tr>
</table>

PawMotors/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PawMotors</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PawMotors.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PawMotors</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Müşteriler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Index">Araçlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Satışlar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PawMotors - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>